apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: bWV0ZW9kYg==
  azurestorageaccountkey: LzdlQUJYdkU1MXQxSGZzRXk3S0tHcnNMV3NPek80NXdKSnBFNVFEazdtZzlZeFVlOEdnTzY2SW10UzNEbjFRUm9PZS80WXdtSXBWUjB0MTFQZ0lzdnc9PQ==
