apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meteodb
  template:
    metadata:
      labels:
        app: meteodb
    spec:
      hostname: meteodb
      volumes:
      - name: weather-data
        azureFile: 
          secretName: azure-secret
          shareName: azure-meteo
          readOnly: false
      containers:
      - name: postgis
        image: postgis/postgis
        volumeMounts:
          - name: weather-data
            mountPath: /weather_data
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: meteodb-postgis-secret
              key: postgis-password
      
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: write-db-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: write-db
            image: mcaciolo/write_db
            volumeMounts:
              - name: weather-data
                mountPath: /weather_data
            env:
            - name: MOUNTED_DATA_PATH
              value: /weather_data
            - name: DB_NAME
              value: postgres
            - name: DB_HOST
              value: meteodb
            - name: DB_PORT
              value: '5432'      
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: meteodb-postgis-secret
                  key: postgis-password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: meteodb-postgis-secret
                  key: postgis-user
